### ISSUE TITLE
Improved Testing

### ISSUE THREAD

**Issue by GochoMugo** [firstprayer/monsql#11]
There is an issue with running these tests. The __username__ and __password__ are hard-coded into the test script. This means that if anyone wants to run the tests, they would have do one of the following:

1. hard-code their credentials into the test script
* create a user with same credentials as specified in the test-script

None of this is easy considering changing the test script would mean entirely different changes among collaborators. Also creating a user may not be possible, say on a CI server.

I suggest we use this approach: allow user running the test to create a credentials file, say named __.credentials.yml__ that will be holds the username and password and that will be added to __.gitignore__ to avoid checking it into git. If the user does __not__ have such a file, particularly CI servers, we try use environment variables instead.

**Comment by firstprayer** [comment]
Good idea. Or to simplify this, we can search for the .credential file first (actually, why not just call test_settings.py? With this user can also specify the db host and username, dbname, etc). If the file is not found, use the default settings (as in the test script now). Setting environment variables is less easy. What do you think?

**Comment by GochoMugo** [comment]
I now understand we need more configuration values apart from the username and password. Is using a python script file the best option in defining such values? I would suggest [yml](http://yaml.org/)

I suggest using environment variables as we prepare to add continuous integration such as Travis CI. This will allow tweaking only environment variables without touching the test script itself, in cases such as moving from a one CI service to another.

**Comment by firstprayer** [comment]
Huh...Interesting. I haven't used Travis CI before, but sounds a good idea. 

I'll try to restructure the test script today. This piece of code will be published to the develop branch

**Comment by firstprayer** [comment]
I got the test scripts restructured. I use a yml file as the config file. It should be easier to test locally now.
