### ISSUE TITLE
Specify MySQL Database Driver

### ISSUE THREAD

**Issue by GochoMugo** [firstprayer/monsql#9]
Which MySQL driver are we supposed to use? There are too many python drivers out there, including this [search](https://pypi.python.org/pypi?%3Aaction=search&term=MySQLdb&submit=search) on [pypi](https://pypi.python.org).

**Comment by firstprayer** [comment]
MySQL Driver? MySQLdb https://pypi.python.org/pypi/MySQL-python is used now.

**Comment by GochoMugo** [comment]
From https://github.com/farcepest/MySQLdb1:
> This is the legacy (1.x) version of MySQLdb. While it is still being maintained, there will not be a lot of new feature development.

Will this bring an issue in the future?

**Comment by firstprayer** [comment]
We're just using the driver to execute SQL. The driver itself doesn't matter that much. Even if we'll switch to a new driver with a completely different interface, we can add a wrapper to the new driver to maintain the consistency of the interface. 

Besides, as far as I know Django also uses this driver. So I think it should be fine. The same works for other db's driver. Whichever seems popular enough is just fine.

**Comment by GochoMugo** [comment]
Those are reasonable points. It is solved then:
- use **MySQLdb** from https://pypi.python.org/pypi/MySQL-python
- install with `pip install MySQL-python`
- more information about the driver be found at https://github.com/farcepest/MySQLdb1
